version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./log:/var/log

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    entrypoint:
      - redis-server
      - "--appendonly"
      - "yes"
